import type { Report, Status } from "../core/types.js";

const EMOJI: Record<Status, string> = { pass: "✅", warn: "⚠️", fail: "❌", "not-applicable": "➖" };

function esc(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
}

export function renderMarkdown(report: Report): string {
  const { input, score, gate } = report;
  const title = input.title ?? input.source;
  const out: string[] = [];
  out.push(`# Muse readiness: ${esc(title)}`);
  out.push("");
  out.push(`**Score: ${score.overall}/100 (${score.grade})**`);
  const sub: string[] = [];
  if (score.directory !== null) sub.push(`Directory readiness: ${score.directory}/100`);
  if (score.custom !== null) sub.push(`Custom-connector readiness: ${score.custom}/100`);
  if (sub.length) out.push("", sub.join(" · "));
  out.push("");
  out.push(gate.passed ? "No blocking failures in auth, injection or network." : `**Blocked by ${gate.blocking.join(", ")}.**`);
  out.push("");
  out.push("| | Check | Result | Severity |");
  out.push("|---|---|---|---|");
  for (const r of report.results) {
    if (r.status === "not-applicable") continue;
    out.push(`| ${EMOJI[r.status]} | **${r.id}** ${esc(r.title)} | ${esc(r.message)} | ${r.severity} |`);
  }
  if (report.probe) {
    out.push("", "## Live probe", "", `Target: \`${esc(report.probe.target || "none")}\`. Only read-only requests were sent.`, "");
    if (report.probe.requests.length) {
      out.push("| Request | Status | Time |", "|---|---|---|");
      for (const r of report.probe.requests) {
        out.push(`| \`${esc(`${r.method} ${r.path}`)}\` | ${r.status ?? esc(r.error?.code ?? "error")} | ${r.ms !== undefined ? `${r.ms} ms` : "–"} |`);
      }
    }
    if (report.probe.skipped.length) {
      out.push("", "Not called:", "");
      for (const s of report.probe.skipped) out.push(`- \`${esc(s.operation)}\`: ${esc(s.reason)}`);
    }
  }
  const detailed = report.results.filter((r) => (r.status === "fail" || r.status === "warn") && r.findings.length);
  if (detailed.length) {
    out.push("", "## Findings", "");
    for (const r of detailed) {
      out.push(`### ${EMOJI[r.status]} ${r.id}: ${esc(r.title)}`, "");
      for (const f of r.findings) out.push(`- ${esc(f.message)}${f.line ? ` (line ${f.line})` : ""}`);
      out.push("", `<sub>Why: ${esc(r.rationale)}</sub>`, "");
    }
  }
  out.push(
    "",
    `<sub>Generated by ${report.tool.name} ${report.tool.version} (ruleset ${report.tool.rulesetDate}) from \`${esc(input.source)}\`. Muse's connector rules are unpublished; these checks reflect public evidence as of the ruleset date.</sub>`,
  );
  return out.join("\n") + "\n";
}
